################################################
# WiFI-Configuration
#
################################################
CIRCUITPY_WIFI_SSID="TP-LINK_7692"
CIRCUITPY_WIFI_PASSWORD="24136440"

################################################
# GENERAL
################################################
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
LOGLEVEL = 20
UART0_TX = "GP0"
UART0_RX = "GP1"
UART1_TX = "GP4"
UART1_RX = "GP5"
UART2_TX = ""
UART2_RX = ""

################################################
# HEART-BEAT
################################################
HEARTBEAT_INTERVAL = 5000
HEARTBEAT_IDLE_INTERVAL = 150
HEARTBEAT_ERROR_INTERVAL = 500
HEARTBEAT_IDLE = 1
HEARTBEAT_ERROR_BMS = 2
HEARTBEAT_ERROR_MODBUS = 3
HEARTBEAT_ERROR_INVERTER = 4
HEARTBEAT_ERROR_WLAN = 5
HEARTBEAT_ERROR_MQTT = 6

################################################
# EPEVER
################################################
EPEVER_DEMO="False"
EPEVER_INTERVAL = 5000
EPEVER_VERSION = "V 0.1.0"
EPEVER_UART=1
EPEVER_BAUD=115200
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
EPEVER_LOGLEVEL=20

################################################
# MQTT-Configuration
################################################
#MQTT_BROKER_IP="<broker-ip-address>"
#MQTT_PORT=1883
#MQTT_PREFIX="RP2040_SOLAR"
#MQTT_TOPIC="<your_topic>"
#MQTT_USER="<your_user"
#MQTT_PW="<users_password>"

MQTT_BROKER_IP="192.168.0.240"
MQTT_PORT=1883
MQTT_PREFIX="RP2040_SOLAR"
MQTT_TOPIC="SOLAR_PICO"
MQTT_USER="lunax"
MQTT_PW="granny.COPTER3opus"
# 10=Debug, 20=Info, 30=Warning, 40=Error, 50=Critical
MQTT_LOGLEVEL=20
